server:
  port: 8888
spring:
  datasource:
#    url: jdbc:mysql://localhost:3306/world?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&wait_timeout=1814400&serverTimezone=Asia/Shanghai
#    url: jdbc:mysql://192.168.40.210:3306/one_vehicle?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&wait_timeout=1814400&serverTimezone=Asia/Shanghai
    url: jdbc:mysql://10.33.27.117:3306/one_vehicle?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
#    password: root
    password: hz_bmcj_123
  main:
    allow-bean-definition-overriding: true

websocket:
  server:
    port:
      17777
