server:
  port: 8888
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/world?autoReconnect=true&useUnicode=true&characterEncoding=utf-8&wait_timeout=1814400&serverTimezone=Asia/Shanghai
    username: root
    password: root
  main:
    allow-bean-definition-overriding: true

websocket:
  server:
    port:
      17777
